### ISSUE TITLE
Question about checkpoint path No such file or directory

### ISSUE THREAD

**Issue by ycc66104116** [qinnzou/DeepCrack#22]
hi, i recently try running DeepCrack, and i encounter some problem that is about checkpoint file. in README.md, it said that i should revised the pretrain_path, however, i only find pretrain_model but no pretrain_path. and i think maybe is because of that i get the following error.
i have checked that file, it's true that the .pth file didn't exit in my checkpoint file. but i can't find why...
does anyone know how to fix this problem? 

in my config.py, i modified the path. maybe someone know if i forget anything to change. 
checkpoint_path = '/content/drive/MyDrive/Colab_Notebooks/DeepCrack/0411/DeepCrack_master/codes/'
log_path = 'log'
pretrained_model = ''
save_format = ''
--------------------my error message----------------------
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main()
  File "train.py", line 172, in main
    cfg.name, epoch, cfg.save_pos_acc, cfg.save_acc))
  File "/content/drive/MyDrive/Colab_Notebooks/DeepCrack/0411/DeepCrack_master/codes/tools/checkpointer.py", line 114, in save
    torch.save(self._get_state(obj), new_filename, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 377, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab_Notebooks/DeepCrack/0411/DeepCrack_master/codes/0428/checkpoints/0428_0428_epoch(1)_acc(0.00000/0.98645)_0000001_2022-04-28-02-27-52.pth'

**Comment by ycc66104116** [comment]
the solution is shown under #20 .
